<?php
return array (
  'version' => array(  
    'app' => array(    
      'default' => array(      
        0 => '001_create_product_categories',
        1 => '002_add_level_to_product_categories',
        2 => '003_create_banners',
        3 => '004_create_bbs_category',
        4 => '005_create_bbs_list',
        5 => '006_create_bbs_comment',
        6 => '007_add_category_image_to_product_categories',
        7 => '008_add_thumb_to_bbs_list',
        8 => '009_add_description_to_bbs_list',
        9 => '010_add_category_banner_and_sort_description_to_product_category',
        10 => '011_create_products',
        11 => '012_add_status_to_products',
        12 => '013_create_product_gallery',
        13 => '014_add_top_seller_to_products',
        14 => '015_create_site_settings',
        15 => '016_add_slug_to_tables',
        16 => '017_add_og_meta_to_site_settings',
        17 => '018_add_googlemap_link_to_site_settings',
        18 => '019_add_keywords_to_site_settings',
        19 => '020_add_slug_to_bbs_category',
        20 => '021_add_title_and_sub_title_to_banners',
        21 => '022_add_product_flags_to_products',
        22 => '023_create_tbl_contact',
        23 => '024_add_youtube_link_to_site_settings',
        24 => '025_add_buying_guide_to_site_settings',
        25 => '026_add_installation_instructions_to_site_settings',
        26 => '027_add_shipping_and_installation_and_construction_process_to_site_settings',
        27 => '028_add_email_level_parent_id_to_bbs_comment',
        28 => '029_add_o_num_to_bbs_list',
        29 => '030_create_product_views',
        30 => '031_create_post_views',
        31 => '032_add_view_count_to_products',
        32 => '033_add_owner_avatar_to_site_settings',
        33 => '034_add_image_url_m_to_banners',
        34 => '035_add_main_intro_to_site_settings',
        35 => '036_add_logo_header_reverse_to_site_settings',
        36 => '037_add_ratio_to_banners',
        37 => '038_add_type_to_bbs_category',
        38 => '039_add_tiktok_link_to_sitesettings',
        39 => '040_create_banner_config',
        40 => '041_add_mobile_columns_to_banner_config',
        41 => '042_add_messenger_link_to_site_settings',
        42 => '043_create_product_category_mapping',
        43 => '044_add_o_num_to_product_categories',
        44 => '045_add_introduction_to_site_settings',
        45 => '046_add_googlemap_links_to_site_settings',
        46 => '047_create_popups_and_popup_images',
      ),
    ),
    'module' => array(    
    ),
    'package' => array(    
      'auth' => array(      
        0 => '001_auth_create_usertables',
        1 => '002_auth_create_grouptables',
        2 => '003_auth_create_roletables',
        3 => '004_auth_create_permissiontables',
        4 => '005_auth_create_authdefaults',
        5 => '006_auth_add_authactions',
        6 => '007_auth_add_permissionsfilter',
        7 => '008_auth_create_providers',
        8 => '009_auth_create_oauth2tables',
        9 => '010_auth_fix_jointables',
        10 => '011_auth_group_optional',
        11 => '012_auth_update_userindex',
      ),
    ),
  ),
  'folder' => 'migrations/',
  'table' => 'migration',
  'flush_cache' => false,
);
